microservice-chart:
  image:
    repository: ghcr.io/pagopa/idpay-self-expense-backend
    tag: latest
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.cstar.pagopa.it

  resources:
    requests:
      memory: "256Mi"
      cpu: "300m"
    limits:
      memory: "4Gi"
      cpu: "500m"

  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 5
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-p-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  envConfig:
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json

    CACHE_REFRESH_MS_RATE: "10000"
    REDIS_CACHE_ENABLED: "true"
    REDIRECT_URI: "https://api-io.cstar.pagopa.it/idpay/self-expense/redirect"
    WEB-VIEW-URL: "https://welfare.cstar.pagopa.it/ricevute/session/<session-id>"
    MIL_AUTH_BASE_URL: "https://api-mcshared.cstar.pagopa.it/auth/token"
