microservice-chart:
  image:
    repository: ghcr.io/pagopa/idpay-merchant
    tag: snapshot-develop@sha256:80a2e40d7b9d5217ef6f3dfbb048db116dc6e877034a6a708f9e9a9453fc8d5d
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.dev.cstar.pagopa.it

  resources:
    requests:
      memory: "768Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "600m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envConfig:
    KEYCLOAK_ADMIN_REDIRECT_URI: "https://dev.bonuselettrodomestici.it/esercente"
    MERCHANT_DEFAULT_INITIATIVES: "68dd003ccce8c534d1da22bc"
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=7
      -Dio.netty.eventLoopThreads=100
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json
      -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n
      -Dcom.sun.management.jmxremote=true
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.rmi.port=3003
      -Djava.rmi.server.hostname=127.0.0.1
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false

  envSecret:
    aks-api-url: cstar-d-itn-dev-aks-apiserver-url

  keyvault:
    name: "cstar-d-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # postman-test:
  #  run: true
  #  repoName: idpay-merchant
  #  dir: postman
  #  collectionName: "idpay-merchant-e2e.postman_collection.json"
  #  envVariablesFile: "idpay_dev.postman_environment.json"
