microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  image:
    repository: ghcr.io/pagopa/idpay-portal-welfare-backend-role-permission
    tag: v1.3.0@sha256:0db89f59e9172e4fe0693bd154139c488632b707e57fbcf3435e8f21c0c71dbe
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.cstar.pagopa.it

  resources:
    requests:
      memory: "768Mi"
      cpu: "150m"
    limits:
      memory: "768Mi"
      cpu: "600m"

  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 5
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-p-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  envConfig:
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=7
      -Dio.netty.eventLoopThreads=100
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
