apiVersion: v2
name: mcshread-datavault
description: MCShared DataVault Helm Chart
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 8.0.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
