microservice-chart:
  image:
    repository: ghcr.io/pagopa/mcshared-datavault
    tag: 3.0.0@sha256:2c076f4f8e43eaf303d4f8f0a679c34f241546565384adc2d01107e03b9172b1
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.uat.cstar.pagopa.it

  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "700m"

  autoscaling:
    enable: true
    minReplica: 8
    maxReplica: 16
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "50"

  envConfig:

  envSecret:
  
  keyvault:
    name: "cstar-u-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
