microservice-chart:
  image:
    repository: ghcr.io/pagopa/mcshared-datavault
    tag: 3.0.1@sha256:904ae3b286a26bf61f34c99244952cf1007c7577c8d5e950b81b4920194a8fb7
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.uat.cstar.pagopa.it

  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1000m"

  autoscaling:
    enable: true
    minReplica: 5
    maxReplica: 16
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "50"

  envConfig:

  envSecret:
  
  keyvault:
    name: "cstar-u-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
