microservice-chart:
  namespace: "idpay"
  nameOverride: "keycloak"
  fullnameOverride: "keycloak"

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /health/live
      port: 9000
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health/ready
      port: 9000
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /keycloak/(.*)


  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true

  envConfig:
    KC_HOSTNAME: "https://idpay.itn.internal.dev.cstar.pagopa.it/keycloak/"
    KC_HTTP_ENABLED: "true"
    KC_PROXY_HEADERS: "xforwarded"
    PROXY_ADDRESS_FORWARDING: "true"
    KC_HEALTH_ENABLED: "true"
    KC_DB_SCHEMA: "public"
    KC_DB: "postgres"



  envSecret:
    KC_BOOTSTRAP_ADMIN_USERNAME: keycloak-bootstrap-username
    KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak-bootstrap-password
    KC_DB_URL: keycloak-postgres-connection-url
    KC_DB_USERNAME: keycloak-postgres-username
    KC_DB_PASSWORD: keycloak-postgres-password

  externalConfigMapValues:
    idpay-common:
      TZ: TZ





  # nodeSelector: {}

  # tolerations: []

  # affinity: {}

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: data
        mountPath: /opt/keycloak/data
      - name: log
        mountPath: /opt/keycloak/log

