microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true
    topologySpreadConstraints:
      create: true
      useDefaultConfiguration: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /idpaytimeline/(.*)

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000

  envConfig:
    MONGODB_DBNAME: "idpay-beneficiari"
    APPLICATIONINSIGHTS_ROLE_NAME: "idpaytimeline"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_SAMPLING_ENABLED: "false"
    APPLICATIONINSIGHTS_SAMPLING_PERCENTAGE: "100"
    DELETE_PAGINATION_SIZE: "100"
    DELETE_DELAY_TIME: "1000"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    HEALTH_MONGO_ENABLED: "false"

  externalConfigMapValues:
    idpay-common:
      TZ: TZ
    idpay-eventhub-01:
      KAFKA_BINDER_BROKER_ENDPOINT_LIST_01: kafka_broker
      KAFKA_TIMELINE_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_TIMELINE_SECURITY_PROTOCOL: kafka_security_protocol
      KAFKA_TOPIC_COMMANDS: idpay_commands_topic
      KAFKA_TOPIC_TIMELINE: idpay_timeline_topic
      KAFKA_GROUP_IN: idpay-timeline-consumer-group

  envSecret:
    MONGODB_URI: mongodb-primary-connection-string
    KAFKA_TIMELINE_OUT_SASL_JAAS_CONFIG: evh-idpay-timeline-idpay-timeline-producer-jaas-config-idpay-01
    KAFKA_TIMELINE_IN_SASL_JAAS_CONFIG: evh-idpay-timeline-idpay-timeline-consumer-jaas-config-idpay-01
    KAFKA_COMMANDS_IN_SASL_JAAS_CONFIG: evh-idpay-commands-idpay-commands-consumer-jaas-config-idpay-01

  # nodeSelector: {}

  tolerations:
    - key: "idpayOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: domain
            operator: In
            values:
            - idpay

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json
