microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true
    topologySpreadConstraints:
      create: true
      useDefaultConfiguration: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /idpayassetregisterbackend/(.*)

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000

  envConfig:
    MONGODB_DBNAME: rdb
    APPLICATIONINSIGHTS_ROLE_NAME: "idpayassetregisterbackend"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "INFO"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    APPLICATIONINSIGHTS_SAMPLING_ENABLED: "false"
    APPLICATIONINSIGHTS_SAMPLING_PERCENTAGE: "100"
    HEALTH_MONGO_ENABLED: "false"
    BLOB_STORAGE_CONTAINER_REFERENCE: "asset"

  externalConfigMapValues:
    idpay-common:
      TZ: TZ
    rest-client:
      ONE_TRUST_PRIVACYNOTICES_BASE_URL: one_trust_privacynotice_base_url
      NOTIFICATION_MS_BASE_URL: email_notification_ms_host
    idpay-eventhub-rdb:
      KAFKA_BROKER: kafka_broker
      KAFKA_CONFIG_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_CONFIG_SECURITY_PROTOCOL: kafka_security_protocol
      KAFKA_ASSET_REGISTER: idpay-asset-register_topic

  envSecret:
    MONGODB_URI: mongodb-primary-connection-string
    ONE_TRUST_TOS_ID: one-trust-tos-id
    ONE_TRUST_API_KEY: one-trust-api-key
    BLOB_STORAGE_CONNECTION_STRING: asset-storage-connection-string
    KAFKA_REGISTER_PRODUCT_FILE_UPLOAD_SASL_JAAS_CONFIG: evh-idpay-asset-register-idpay-asset-register-consumer-jaas-config-idpay-rdb

  # nodeSelector: {}

  tolerations:
    - key: "idpayOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: domain
            operator: In
            values:
            - idpay

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json
