microservice-chart:
  image:
    repository: ghcr.io/pagopa/idpay-merchant
    tag: snapshot-uat
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.uat.cstar.pagopa.it

  resources:
    requests:
      memory: "1Gi"
      cpu: "150m"
    limits:
      memory: "1Gi"
      cpu: "600m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envConfig:
    KEYCLOAK_ADMIN_REDIRECT_URI: "https://uat.bonuselettrodomestici.it/esercente"
    MERCHANT_DEFAULT_INITIATIVES: "68dd003ccce8c534d1da22bc"
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-u-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  postman-test:
    run: true
    repoName: idpay-merchant
    dir: postman
    collectionName: "idpay-merchant-e2e.postman_collection.json"
    envVariablesFile: "idpay_uat.postman_environment.json"
