microservice-chart:
  image:
    repository: ghcr.io/pagopa/idpay-timeline
    tag: snapshot-fix-kafka-instrumentation
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.dev.cstar.pagopa.it

  resources:
    requests:
      memory: "150Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
      - type: memory
        metadata:
          type: Utilization
          value: "90"

  envSecret:
    aks-api-url: cstar-d-itn-dev-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-d-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

 # postman-test:
 #   run: true
 #   repoName: idpay-timeline
 #   dir: postman
 #   collectionName: "idpay-timeline-e2e.postman_collection.json"
 #   envVariablesFile: "idpay_dev.postman_environment.json"
