microservice-chart:
  image:
    repository: ghcr.io/pagopa/mcshared-datavault
    tag: 3.2.5@sha256:130e722be2b73b38c06251490cbc555ae633da80c53b6eb192bc5326f2edea6d
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.uat.cstar.pagopa.it

  resources:
    requests:
      memory: "256Mi"
      cpu: "1000m"
    limits:
      memory: "512Mi"
      cpu: "2000m"

  deployment:
    replicas: 1 # This value must be set equal to autoscaling.minReplica

  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 3
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "60"
      - type: memory
        metadata:
          type: Utilization
          value: "90"

  envConfig:

  envSecret:

  keyvault:
    name: "cstar-u-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
