microservice-chart:
  image:
    repository: ghcr.io/pagopa/idpay-admissibility-assessor
    tag: snapshot-uat
    pullPolicy: Always

  ingress:
    host: idpay.itn.internal.uat.cstar.pagopa.it

  resources:
    requests:
      memory: "2Gi"
      cpu: "300m"
    limits:
      memory: "4Gi"
      cpu: "500m"

  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 6
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "70"
      - type: memory
        metadata:
          type: Utilization
          value: "75"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key
    PAGOPA_PDND_CONFIGURATION_JWT_KEY_C001: pagopa-pdnd-configuration-jwt-key-c001
    PAGOPA_PDND_CONFIGURATION_AGID_JWT_PUB_C001: pagopa-pdnd-configuration-agid-jwt-pub-c001
    PAGOPA_PDND_CONFIGURATION_CLIENT_ID_C001: pagopa-pdnd-configuration-client-id-c001
    PAGOPA_PDND_CONFIGURATION_KID_C001: pagopa-pdnd-configuration-kid-c001
    PAGOPA_PDND_CONFIGURATION_PURPOSE_ID_C001: pagopa-pdnd-configuration-purpose-id-c001
    PAGOPA_PDND_CONFIGURATION_JWT_KEY_C021: pagopa-pdnd-configuration-jwt-key-c021
    PAGOPA_PDND_CONFIGURATION_AGID_JWT_PUB_C021: pagopa-pdnd-configuration-agid-jwt-pub-c021
    PAGOPA_PDND_CONFIGURATION_CLIENT_ID_C021: pagopa-pdnd-configuration-client-id-c021
    PAGOPA_PDND_CONFIGURATION_KID_C021: pagopa-pdnd-configuration-kid-c021
    PAGOPA_PDND_CONFIGURATION_PURPOSE_ID_C021: pagopa-pdnd-configuration-purpose-id-c021
#    INPS_CLIENT_CERT_STRING: pagopa-inps-client-cert-string
#    INPS_CLIENT_KEY_PEM: pagopa-inps-client-key-pem

  keyvault:
    name: "cstar-u-itn-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  envConfig:
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=30.0
      -XX:MaxRAMPercentage=65.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json
    CACHE_REFRESH_MS_RATE: "10000"
    REDIS_CACHE_ENABLED: "true"

    PDND_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/pdnd
    PDND_ACCESS_TOKEN_AUDIENCE: auth.uat.interop.pagopa.it/client-assertion


    ANPR_ENV: uat
    ANPR_AUTH_USERID: pagopa-idpay
    #ANPR_BASE_URL: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND
    ANPR_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/anpr

    #TODO Now we are using MOCK on APIM for ISEE
    INPS_ISEE_CONSULTATION_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/inps/soap
